#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely.
# It also handles the SIGTERM signal and prints "I am invincible!!!"

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done

